version       = "0.2.0"
author        = "Andre von Houck"
description   = "Silky immediate mode UI graphics."
license       = "MIT"

srcDir        = "src"

requires "nim >= 2.2.4"
requires "pixie"
requires "shady"
requires "vmath"
requires "windy"
requires "dx12"
requires "vk14"
requires "metal4"
requires "chroma"
requires "bumpy"
requires "jsony"
requires "fluffy"
